/*
 ==============================================================================
 
 AudioEngine.cpp
 Created: 30 Aug 2021 10:45:03am
 Author:  Thomas Hézard
 
 ==============================================================================
 */


#include "AudioEngine.h"


void AudioEngine::prepareResources(int maxSamplesPerBlock, double sampleRate) {
    
    sineWaveGenerator_.setSampleRate(sampleRate);
}


void AudioEngine::releaseResources() {
}


void AudioEngine::generateAudioData(float **outputAudioData, int numChannels, int numSamples) {
    
    // TO DO 
    // Fill outputAudioData with sine wave generated by sineWaveGenerator_.
    // Put the same data in all channels.
    
}


void AudioEngine::setSineWaveFrequency(float frequency) {
    
    sineWaveGenerator_.setFrequency(frequency);
}


float AudioEngine::getSineWaveFrequency() const {
    
    return sineWaveGenerator_.getFrequency();
}
